ASPMVCCRUD/Models/AddEmployeeViewModel.cs
namespace ASPMVCCRUD.Models
{
    public class AddEmployeeViewModel
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public long Salary { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Department { get; set; }

    }
}

ASPMVCCRUD/Models/Domain/Employee.cs
namespace ASPMVCCRUD.Models.Domain
{
    // sekrang mari buat beberapa properti untuk karyawan
    public class Employee
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public long Salary { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Department { get; set; }

    }
}
 

ASPMVCCRUD/Models/ErrorViewModel.cs
namespace ASPMVCCRUD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASPMVCCRUD/Models/UpdateEmployeeViewModel.cs
namespace ASPMVCCRUD.Models
{
    //sekrang membuat tampilan model
    public class UpdateEmployeeViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public long Salary { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Department { get; set; }
    }
}

ASPMVCCRUD/Controllers/EmployeesController.cs
using ASPMVCCRUD.Data;
using ASPMVCCRUD.Models;
using ASPMVCCRUD.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ASPMVCCRUD.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly MVCDEMODbContext mVCDEMODbContext;

        public EmployeesController(MVCDEMODbContext mVCDEMODbContext)
        {
            this.mVCDEMODbContext = mVCDEMODbContext; // dengan membuat ini, bisa private readonly dan connect databse
        }

        // Membuat fungsi get untuk menampilkan ke layar
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var empolyees = await mVCDEMODbContext.Employees.ToListAsync();
            return View(empolyees);
        }


        // buat fungsi untuk menambahkan karyawan
        // setelah itu kita dpat menampilkan nya ke layar
        //sdsdaasd 
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddEmployeeViewModel addEmployeeRequest)
        //properti ini akan require paramater
        //Add(AddEmployeeViewModel addEmployeeRequest), menerima method yang lalu diberi nama nya
        {
            //1. harus mengubah dari AddEmployeeViewModel -> AddEmployessController
            var employee = new Employee()
            {
                Id = Guid.NewGuid(), //karena ingin menetepkan nilai id, maka require langsung dari guid
                Name = addEmployeeRequest.Name,
                Email = addEmployeeRequest.Email,
                Salary = addEmployeeRequest.Salary,
                Department = addEmployeeRequest.Department,
                DateOfBirth = addEmployeeRequest.DateOfBirth,

                //setelah membuat ini, saat nya memasukkan ke dlam database
            };

            await mVCDEMODbContext.Employees.AddAsync(employee);
            await mVCDEMODbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var employee = await mVCDEMODbContext.Employees.FirstOrDefaultAsync(x => x.Id == id);

            if(employee != null)
            {
                // membuat variabel yang akan mengarahkan ke UpdateEmployeeViewModel
                var viewModel = new UpdateEmployeeViewModel()
                {
                    Id = employee.Id, 
                    Name = employee.Name,
                    Email = employee.Email,
                    Salary = employee.Salary,
                    Department = employee.Department,
                    DateOfBirth = employee.DateOfBirth,
                };
                return await Task.Run(() => View("View", viewModel));
            }

            return View(employee); 
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateEmployeeViewModel model)
        { 
            // mengambil data dari databse terlebih dahalu
            var employee = await mVCDEMODbContext.Employees.FindAsync(model.Id);

            if (employee != null)
            { 
                employee.Name = model.Name;
                employee.Email = model.Email;
                employee.Salary = model.Salary;
                employee.DateOfBirth = model.DateOfBirth;
                employee.Department = model.Department;

                await mVCDEMODbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateEmployeeViewModel model)
        {
            var employee = await mVCDEMODbContext.Employees.FindAsync(model.Id);  

            if (employee != null)
            {
                mVCDEMODbContext.Employees.Remove(employee);

                await mVCDEMODbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return RedirectToAction("index");
        }
    }
} 

ASPMVCCRUD/Controllers/HomeController.cs
using ASPMVCCRUD.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ASPMVCCRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASPMVCCRUD/Views/Employees/Add.cshtml
@model ASPMVCCRUD.Models.AddEmployeeViewModel

@{
}

<h1 class="mt-3">Add Employee</h1>
<form method="post" action="Add" class="mt-5">
    @* akan pergi ke method Post yang dimana letak di Controller *@
    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="type" class="form-control" asp-for="Name">
        @* Mengartikan bahwa box label terdapat fungsi *@
        @* untuk properti "Name" begitu dengan lain nya *@
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Email Address</label>
        <input type="email" class="form-control" asp-for="Email">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Salary</label>
        <input type="number" class="form-control" asp-for="Salary">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Date Of Birth</label>
        <input type="date" class="form-control" asp-for="DateOfBirth">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Department</label>
        <input type="text" class="form-control" asp-for="Department">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

ASPMVCCRUD/Views/Employees/Index.cshtml
@model List<ASPMVCCRUD.Models.Domain.Employee> // mengambil database dari Employee
@{
}

<h1>Employees</h1>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Salary</th>
            <th>Date Of Birth</th>
            <th>Department</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model) // membuat perulangan untuk tampilkan data
        {
            <tr>
                <td>@employee.Id</td>
                <td>@employee.Name</td>
                <td>@employee.Email</td>
                <td>@employee.Salary</td>
                <td>@employee.DateOfBirth.ToString("dd-MM-yyyy")</td>
                <td>@employee.Department</td>
                <td><a href="Employees/View/@employee.Id">View</a></td>
                @*Fungsi bisa melihat detail dari pemilihan id*@        
            </tr>
        }
    </tbody>
</table>

ASPMVCCRUD/Views/Employees/View.cshtml
@model ASPMVCCRUD.Models.UpdateEmployeeViewModel
@{
}

<h1 class="mt-3">Edit Employee</h1>
<form method="post" action="View" class="mt-5">
    <div class="mb-3">
        <label for="" class="form-label">Id</label>
        <input type="type" class="form-control" asp-for="Id" readonly>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Name">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Email Address</label>
        <input type="email" class="form-control" asp-for="Email">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Salary</label>
        <input type="number" class="form-control" asp-for="Salary">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Date Of Birth</label>
        <input type="date" class="form-control" asp-for="DateOfBirth">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Department</label>
        <input type="text" class="form-control" asp-for="Department">
    </div>
    <button type="submit" class="btn btn-primary">Save Update</button>
    <button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="Employees">Delete</button>
</form>

ASPMVCCRUD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASPMVCCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPMVCCRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPMVCCRUD.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPMVCCRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Add">Add Employee</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ASPMVCCRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>